packages:
  - docs
catalog:
  '@iconify/json': ^2.2.315
  '@types/node': ^22.13.10
  '@vinicunca/eslint-config': ^3.7.2
  '@vinicunca/unocss-preset': ^1.9.0
  '@vitest/coverage-v8': ^3.0.8
  bumpp: ^10.0.3
  eslint: ^9.22.0
  fuse.js: ^7.1.0
  postcss-nested: ^7.0.2
  prettier: ^3.5.3
  radix-vue: ^1.9.17
  taze: ^18.7.1
  tiny-invariant: ^1.3.3
  tsup: ^8.4.0
  type-fest: ^4.37.0
  typedoc: ^0.27.9
  typescript: ^5.8.2
  unocss: ^66.0.0
  unplugin-vue-components: ^28.4.1
  vitepress: ^1.6.3
  vitest: ^3.0.8
