packages:
  - docs
catalog:
  '@iconify/json': ^2.2.360
  '@types/node': ^22.16.5
  '@vinicunca/eslint-config': ^3.18.0
  '@vinicunca/unocss-preset': ^1.16.1
  '@vitest/coverage-v8': ^3.2.4
  bumpp: ^10.2.0
  eslint: ^9.31.0
  fuse.js: ^7.1.0
  postcss-nested: ^7.0.2
  prettier: ^3.6.2
  radix-vue: ^1.9.17
  taze: ^19.1.0
  tiny-invariant: ^1.3.3
  tsup: ^8.5.0
  type-fest: ^4.41.0
  typedoc: ^0.28.7
  typescript: ^5.8.3
  unocss: ^66.3.3
  unplugin-vue-components: ^28.8.0
  vitepress: ^1.6.3
  vitest: ^3.2.4
