catalog:
  '@iconify/json': ^2.2.307
  '@types/node': ^22.13.4
  '@vinicunca/eslint-config': ^3.0.0
  '@vinicunca/unocss-preset': ^1.1.4
  '@vitest/coverage-v8': ^3.0.5
  bumpp: ^10.0.3
  eslint: ^9.20.1
  fuse.js: ^7.1.0
  postcss-nested: ^7.0.2
  prettier: ^3.5.1
  radix-vue: ^1.9.14
  taze: ^18.5.0
  tiny-invariant: ^1.3.3
  tsup: ^8.3.6
  type-fest: ^4.34.1
  typedoc: ^0.27.7
  typescript: ^5.7.3
  unocss: ^65.5.0
  unplugin-vue-components: ^28.1.0
  vitepress: ^1.6.3
  vitest: ^3.0.5
packages:
  - docs
