catalog:
  '@iconify/json': ^2.2.291
  '@types/node': ^22.10.5
  '@vinicunca/eslint-config': ^2.15.5
  '@vinicunca/unocss-preset': ^1.1.1
  '@vitest/coverage-v8': ^2.1.8
  bumpp: ^9.9.2
  eslint: ^9.17.0
  fuse.js: ^7.0.0
  postcss-nested: ^7.0.2
  prettier: ^3.4.2
  radix-vue: ^1.9.12
  taze: ^0.18.0
  tiny-invariant: ^1.3.3
  tsup: ^8.3.5
  type-fest: ^4.31.0
  typedoc: ^0.27.6
  typescript: ^5.7.2
  unocss: ^0.65.3
  unplugin-vue-components: ^0.28.0
  vitepress: ^1.5.0
  vitest: ^2.1.8
packages:
  - docs
