/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    PerkakasBadge: typeof import('./.vitepress/components/perkakas-badge.vue')['default']
    PerkakasDesc: typeof import('./.vitepress/components/perkakas-desc.vue')['default']
    PerkakasItem: typeof import('./.vitepress/components/perkakas-item.vue')['default']
    PerkakasPage: typeof import('./.vitepress/components/perkakas-page.vue')['default']
    PerkakasParameters: typeof import('./.vitepress/components/perkakas-parameters.vue')['default']
    PerkakasTags: typeof import('./.vitepress/components/perkakas-tags.vue')['default']
  }
}
