/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    DocsBox: typeof import('./.vitepress/components/docs-box.vue')['default']
    DocsTooltip: typeof import('./.vitepress/components/docs-tooltip.vue')['default']
    EslintConfigHeading: typeof import('./.vitepress/components/eslint-config-heading.vue')['default']
    EslintIgnoreList: typeof import('./.vitepress/components/eslint-ignore-list.vue')['default']
    EslintList: typeof import('./.vitepress/components/eslint-list.vue')['default']
    EslintRuleItem: typeof import('./.vitepress/components/eslint-rule-item.vue')['default']
    EslintRuleName: typeof import('./.vitepress/components/eslint-rule-name.vue')['default']
    PerkakasBadge: typeof import('./.vitepress/components/perkakas-badge.vue')['default']
    PerkakasDesc: typeof import('./.vitepress/components/perkakas-desc.vue')['default']
    PerkakasItem: typeof import('./.vitepress/components/perkakas-item.vue')['default']
    PerkakasParameters: typeof import('./.vitepress/components/perkakas-parameters.vue')['default']
    PerkakasTags: typeof import('./.vitepress/components/perkakas-tags.vue')['default']
  }
}
